# Numpy
The scikit-learn library requires input tables of 2-dimensional NumPy arrays

In [1]:
import numpy as np

# produce numpy array of 10 digits
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# shape of array
array_1 = np.arange(10)
array_1.shape

(10,)

In [7]:
# reshape the array
array_1= array_1.reshape((5,2))
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
array_1.shape

(5, 2)

In [9]:
array_1.ndim

2

In [10]:
# add 1 to every element of the array by broadcasting
array_1+1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# element wise multiplication
array_2= np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
(array_2**2).reshape(5,2)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])