# Numpy
## Initializing Numpy arrays

In [1]:
import numpy as np

In [9]:
np.arange(10).reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
# Initialize an array of zeros with np.zeros
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
# initialize array of ones using np.ones. introduce dtype 
np.ones((5,2), dtype= int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [7]:
# use np.empty to allocate memory for an array
np.empty((5,2), dtype= float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Indexing